env:
  max_steps: 50
  starting_state: 'CC'
  reward_type: 'QED'
  reward_discount: 0.7 # Closer rewards discounted more
  fix_starting_state: False
  atom_vocab: {'C','O','N','P'}
  allowed_ring_sizes: [3,4,5,6]
  allow_inter_ring_bond: False

agent:
  device: 'cuda:0'
  lr: 1.0e-4
  hid_ds: [2049, 1024, 512, 256, 128, 1]
  batch_size: 16
  update_tgt: 20
  reward_discount: 0.95
  tgt_net_weight_multiplier: 0.995
  search_epsilon: 1.0 # 1.0 = 100% chance to take random action
  search_epsilon_scalar: 0.9995 # How much to reduce search eps every step
  
max_steps: 40
epochs: 5000
update_step: 20
fingerprint_radius: 3
fingerprint_len: 2048

log_path: 'tb_logs'